name: barry_mobile_hud_live
packages:
  - apps/**
  - packages/**

scripts:
  analyze: melos exec --concurrency=1 -- flutter analyze
  test: melos exec --concurrency=1 --dir-exists=test -- flutter test
