name: barry_platform_bridge
version: 0.1.0
publish_to: none
environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.barry.platform_bridge
        pluginClass: BarryPlatformBridgePlugin
      ios:
        pluginClass: BarryPlatformBridgePlugin

dev_dependencies:
  flutter_lints: ^4.0.0
